/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MakingChaiImport } from './routes/makingChai'
import { Route as AboutImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppDasboardImport } from './routes/app/dasboard'
import { Route as ProductPidImport } from './routes/Product.$pid'

// Create Virtual Routes

const ProductsLazyImport = createFileRoute('/Products')()

// Create/Update Routes

const ProductsLazyRoute = ProductsLazyImport.update({
  id: '/Products',
  path: '/Products',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Products.lazy').then((d) => d.Route))

const MakingChaiRoute = MakingChaiImport.update({
  id: '/makingChai',
  path: '/makingChai',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppDasboardRoute = AppDasboardImport.update({
  id: '/dasboard',
  path: '/dasboard',
  getParentRoute: () => AppRouteRoute,
} as any)

const ProductPidRoute = ProductPidImport.update({
  id: '/Product/$pid',
  path: '/Product/$pid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/makingChai': {
      id: '/makingChai'
      path: '/makingChai'
      fullPath: '/makingChai'
      preLoaderRoute: typeof MakingChaiImport
      parentRoute: typeof rootRoute
    }
    '/Products': {
      id: '/Products'
      path: '/Products'
      fullPath: '/Products'
      preLoaderRoute: typeof ProductsLazyImport
      parentRoute: typeof rootRoute
    }
    '/Product/$pid': {
      id: '/Product/$pid'
      path: '/Product/$pid'
      fullPath: '/Product/$pid'
      preLoaderRoute: typeof ProductPidImport
      parentRoute: typeof rootRoute
    }
    '/app/dasboard': {
      id: '/app/dasboard'
      path: '/dasboard'
      fullPath: '/app/dasboard'
      preLoaderRoute: typeof AppDasboardImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppDasboardRoute: typeof AppDasboardRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDasboardRoute: AppDasboardRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/makingChai': typeof MakingChaiRoute
  '/Products': typeof ProductsLazyRoute
  '/Product/$pid': typeof ProductPidRoute
  '/app/dasboard': typeof AppDasboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/makingChai': typeof MakingChaiRoute
  '/Products': typeof ProductsLazyRoute
  '/Product/$pid': typeof ProductPidRoute
  '/app/dasboard': typeof AppDasboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/makingChai': typeof MakingChaiRoute
  '/Products': typeof ProductsLazyRoute
  '/Product/$pid': typeof ProductPidRoute
  '/app/dasboard': typeof AppDasboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/makingChai'
    | '/Products'
    | '/Product/$pid'
    | '/app/dasboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/about'
    | '/makingChai'
    | '/Products'
    | '/Product/$pid'
    | '/app/dasboard'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/about'
    | '/makingChai'
    | '/Products'
    | '/Product/$pid'
    | '/app/dasboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  MakingChaiRoute: typeof MakingChaiRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
  ProductPidRoute: typeof ProductPidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  MakingChaiRoute: MakingChaiRoute,
  ProductsLazyRoute: ProductsLazyRoute,
  ProductPidRoute: ProductPidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/app",
        "/about",
        "/makingChai",
        "/Products",
        "/Product/$pid"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/app": {
      "filePath": "app/route.jsx",
      "children": [
        "/app/dasboard"
      ]
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/makingChai": {
      "filePath": "makingChai.jsx"
    },
    "/Products": {
      "filePath": "Products.lazy.jsx"
    },
    "/Product/$pid": {
      "filePath": "Product.$pid.jsx"
    },
    "/app/dasboard": {
      "filePath": "app/dasboard.jsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
